config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/my_posts', to: 'feeds#user_index'
  resources :posts, only: [] do
    resources :comments, only: :create
  end
  resources :feeds, path: :feed, only: [:index]
  resources :tasks, only: [:new, :create, :show, :index, :update]
  resources :questions, only: [:new, :create, :show, :index]

  patch "/users/:id/upvotes", to: "upvotes#update", as: :user_upvote

  resources :events, only: [:new, :create, :show, :index] do
    resources :attendances, only: [:create]
  end

  resources :attendances, only: [:destroy]
  resources :notifications, only: [:update]

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  include Mappable
  before_action :localheroes, only: [:index, :show, :user_index]
  layout "sidebar_layout_show", only: [:show, :index, :user_index]

  def index
    @posts = Post.all.order(created_at: :desc)
    @events = Event.all.order(created_at: :desc)
    @questions = Question.all.order(created_at: :desc)
    @tasks = Task.all.order(created_at: :desc)

    @users = User.where.not(latitude: nil, longitude: nil)
  end

  def user_index
    @user_posts = Post.where(user: current_user)
    @users = User.where.not(latitude: nil, longitude: nil)
  end

  private

  def localheroes
    # Methods for retrieving top and most recent localheroes
    @top_localheroes = User.order('votes DESC').limit(3)
    @recent_localheroes = User.order('created_at DESC').limit(3)
  end
end

app/views/feeds/_events_card.html.erb
<%= link_to event_path(post),  class: "text-dec-none" do %>
  <div class="card-post event">


    <div class="card-post-content">
      <div class="card-post-upper-part">
        <div class="card-post-header">
          <%= image_tag("event.png", class: "label") %>
          <h2><%= post.title %></h2>
        </div>
        <div class="card-post-body">
            <p><i class="fas fa-map-marker-alt">&nbsp</i><%= post.address %></p>
            <p><i class="far fa-clock"></i> <%= post.starts_at.to_s(:long_ordinal) %></p>

        </div>
      </div>
      <div class="card-post-footer">

          <%= cl_image_tag post.user.photo.url(:bright_face), class: "post-show-avatar inline" %>

          <div class="dropdown">
            <% if post.user.votes >= 30 %>
            <h5><%= post.user.first_name %><span>🏆</span></h5>
            <% else %>
            <h5><%= post.user.first_name %></h5>
            <% end %>
            <div class="dropdown-content">
              <% if post.user.content.nil? %>
              <p> No information about me currently</p>
              <% else %>
              <p><strong> About me: </strong><%= post.user.content %></p>
              <% end %>
            </div>
          </div>

      </div>
    </div>

    <div class="card-post-photo">
      <% if post.photo? %>
      <%= cl_image_tag post.photo, class: "post_image" %>
      <% else %>
      <%= image_tag "https://images.unsplash.com/photo-1526891993611-eca1e7d7b582?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80", class: "post_image" %>
      <% end %>
      <p><%= post.participants.count %> neighbours are going</p>
    </div>
  </div>
<% end %>

app/views/feeds/_questions_card.html.erb
<%= link_to question_path(post),  class: "text-dec-none" do %>
<div class="card-post question">
  <div class="card-post-content">
    <div class="card-post-header">
      <%= image_tag("question.png", class: "label") %>
      <h2><%= post.title %></h2>
    </div>
    <div class="card-post-body">
      <p><%= post.content %></p>
    </div>
    <div class="card-post-footer-question">
      <div class="card-post-footer">
        <%= cl_image_tag post.user.photo.url(:bright_face), class: "post-show-avatar inline" %>
        <div class="dropdown">
          <% if post.user.votes >= 30 %>
          <h5><%= post.user.first_name %><span>🏆</span></h5>
          <% else %>
          <h5><%= post.user.first_name %></h5>
          <% end %>
          <div class="dropdown-content">
            <% if post.user.content.nil? %>
            <p> No information about me currently</p>
            <% else %>
            <p><strong> About me: </strong><%= post.user.content %></p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-post-photo answer-position">
       <p><%= post.comments.count %> answers</p>
     </div>
   </div>
 </div>

</div>
<% end %>

app/views/feeds/_tasks_card.html.erb
<%= link_to task_path(post),  class: "text-dec-none" do %>
<div class="card-post task">


  <div class="card-post-content">
    <div class="card-post-upper-part">
      <div class="card-post-header">
        <%= image_tag("task.png", class: "label") %>
        <h2><%= post.title %></h2>
      </div>
      <div class="card-post-body">
        <p><%= post.content %></p>
      </div>
    </div>
    <div class="card-post-footer">

      <%= cl_image_tag post.user.photo.url(:bright_face), class: "post-show-avatar inline" %>

      <div class="dropdown">
        <% if post.user.votes >= 30 %>
        <h5><%= post.user.first_name %><span>🏆</span></h5>
        <% else %>
        <h5><%= post.user.first_name %></h5>
        <% end %>
        <div class="dropdown-content">
          <% if post.user.content.nil? %>
          <p> No information about me currently</p>
          <% else %>
          <p><strong> About me: </strong><%= post.user.content %></p>
          <% end %>
        </div>
      </div>

    </div>
  </div>

  <div class="card-post-photo">
    <% if post.photo? %>
    <%= cl_image_tag post.photo, class: "post_image" %>
    <% else %>
    <%= image_tag "https://images.unsplash.com/photo-1526891993611-eca1e7d7b582?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80", class: "post_image" %>
    <% end %>
    <p>
      <% if post.done %>
      <%= "Completed " %><i class="fas fa-check check-green"></i>
      <% else %>
      <%= "Still need a hand!" %>
      <% end %>
    </p>
  </div>
</div>
<% end %>

app/views/feeds/index.html.erb
<% @posts.each do |post| %>
<% if post.type == "Event" %>
<%= render 'feeds/events_card', post: post %>

<% elsif post.type == "Question" %>
<%= render 'feeds/questions_card', post: post %>

<% else %>
<%= render 'feeds/tasks_card', post: post %>
<% end %>
<% end %>

app/views/feeds/user_index.html.erb
<% @user_posts.each do |post| %>
<% if post.type == "Event" %>
<%= render 'feeds/events_card', post: post %>

<% elsif post.type == "Question" %>
<%= render 'feeds/questions_card', post: post %>

<% else %>
<%= render 'feeds/tasks_card', post: post %>
<% end %>
<% end %>