config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/my_posts', to: 'feeds#user_index'
  resources :posts, only: [] do
    resources :comments, only: :create
  end
  resources :feeds, path: :feed, only: [:index]
  resources :tasks, only: [:new, :create, :show, :index, :update]
  resources :questions, only: [:new, :create, :show, :index]

  patch "/users/:id/upvotes", to: "upvotes#update", as: :user_upvote

  resources :events, only: [:new, :create, :show, :index] do
    resources :attendances, only: [:create]
  end

  resources :attendances, only: [:destroy]
  resources :notifications, only: [:update]

end

app/models/event.rb
class Event < Post
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Mappable
  include Localheroable

  layout "sidebar_layout_show", only: [:show, :index]

  def index
    @events = Event.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
    @event_attendance = @event.attendances.find_by(user: current_user)
    @comment = Comment.new
    @post = @event.becomes(Post)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :photo, :content, :starts_at, :address)
  end
end

app/views/events/_events_only_card.html.erb
<%= link_to event_path(event),  class: "text-dec-none" do%>
  <div class="card-post">
    <div class="label label-info label-abs"><i class="fas fa-calendar-alt"> </i> <%= event.type %></div>
    <div class="card-post-infos">
      <div>
        <h2 id="card-post-info-header"><%= event.title %></h2>
        <p id="card-post-info-content"><%= event.content %></p>

        <p id="card-post-address"> <strong> Where at: </strong> <%= event.address %></p>
        <p id="card-post-starts-at"> <strong> When: </strong> <%= event.starts_at.to_s(:long_ordinal) %></p>
    <% if event.photo? %>
    <%= cl_image_tag event.photo, :class => "post_image" %>
    <% else %>
    <%= image_tag "https://images.unsplash.com/photo-1484494789010-20fc1a011197?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80", :class => "post_image" %>
    <% end %>
      </div>

    </div>
  </div>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
<%= render 'feeds/events_card', post: event %>
<% end %>

app/views/events/new.html.erb
<div class="container">
  <div class="card-form">
    <div class="card-form-infos">
      <%= render 'shared/tabs_new_post' %>
      <em><p>Create a new local gathering for your community</p></em>
        <%= simple_form_for(@event) do |f| %>
          <strong><%= f.input :title %></strong>
          <strong><%= f.input :content, :label => "Description" %></strong>
          <strong><%= f.input :starts_at, :label => "Your event begins at" %></strong>
          <strong><%= f.input :address, :label => "Event location" %></strong>

          <%= f.input :photo, input_html: { class: 'hidden' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit :submit, class: "btn btn-info", value: "Submit"  %>
        <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-card-1">
  <%= cl_image_tag @event.photo %>
  <div class="date-card">
    <p><i class="fas fa-calendar-day"></i><strong><%= @event.starts_at.to_time.strftime('%B %e') %></strong></p>
  </div>
  <div class="event-information3">
    <div class="event-information">
      <div class="event-card-body">
        <h4><%= @event.title %></h4>
        <div class="event-card-address">
          <p><i class="fas fa-map-marker-alt"></i>&nbsp<%= @event.address %></p>
          <p><i class="far fa-clock"></i><%= @event.starts_at.to_time.strftime('%l:%M %p') %></p>
        </div>
    </div>

        <div class="gridcontainer">
          <%= cl_image_tag @event.user.photo.url(:bright_face), class: "event-show-avatar" %>
          <% if @event.user.votes >= 30 %>
          <p><%= @event.user.first_name %><span>🏆</span></p>
          <% else %>
          <p><%= @event.user.first_name %></p>
          <% end %>
          <div class="all-cards-upvote">
            <%= render 'shared/upvote', comment: @event %>
          </div>
      </div>

    </div>
    <div class="event-information2">
          <% if @event_attendance %>
            <%= link_to attendance_path(@event_attendance), class: "btn btn-info white-text ticked", method: :delete do %>
            You're going <i class="fas fa-check check-green"></i>
            <% end %>
          <% else %>
            <p><%= link_to "I am going!", event_attendances_path(@event), class: "btn btn-info white-text", method: :post %></p>
          <% end %>
        <div class="event-attendances">
          <p><strong><%= @event.participants.count %></strong> neighbours are going</p>
        </div>

    </div>
</div>
  </div>
  <div class="event-card-2">
    <div class="event-card-header">
      <h5>Details</h5>
    </div>
    <p><%= @event.content %></p>
  </div>
  <%= render 'shared/comments_section', comment: @comment, post: @post %>