config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  get '/my_posts', to: 'feeds#user_index'
  resources :posts, only: [] do
    resources :comments, only: :create
  end
  resources :feeds, path: :feed, only: [:index]
  resources :tasks, only: [:new, :create, :show, :index, :update]
  resources :questions, only: [:new, :create, :show, :index]

  patch "/users/:id/upvotes", to: "upvotes#update", as: :user_upvote

  resources :events, only: [:new, :create, :show, :index] do
    resources :attendances, only: [:create]
  end

  resources :attendances, only: [:destroy]
  resources :notifications, only: [:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, length: { minimum: 10 }

  def notify!(actor)
    Notification.create(
      recipient: post.user,
      actor: actor,
      action: 'commented',
      post: post
    ) unless post.user == actor
  end
end

app/models/event.rb
class Event < Post
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :post
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"

  scope :unread, -> { where read: false }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :attendances
  has_many :participants, through: :attendances, source: :user
  has_many :comments

  mount_uploader :photo, PhotoUploader
end

app/models/question.rb
class Question < Post
end

app/models/task.rb
class Task < Post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :tasks
  has_many :questions
  has_many :events
  has_many :comments
  has_many :notifications, foreign_key: :recipient_id

  has_many :attendances
  has_many :attended_events, -> { where(type: "Event") }, through: :attendances, source: :post
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def upvote!
    update(votes: votes + 1)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # Use mappable and localheroable concerncs
  include Mappable
  include Localheroable
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      @comment.notify!(current_user)
      redirect_to helpers.determine_post_path(@post)
    else
      rerender_original_show
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def rerender_original_show
    type = @post.type
    # Metaprogramming magic
    instance_variable_set "@#{type.downcase}",
                          @post.becomes(type.safe_constantize)
    @post = @post.becomes(Post) # ensure type for generic comment form
    localheroes # Use concern instead of method duplication
    render params[:origin_view], layout: "sidebar_layout_show"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Mappable
  include Localheroable

  layout "sidebar_layout_show", only: [:show, :index]

  def index
    @events = Event.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
    @event_attendance = @event.attendances.find_by(user: current_user)
    @comment = Comment.new
    @post = @event.becomes(Post)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :photo, :content, :starts_at, :address)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  include Mappable
  before_action :localheroes, only: [:index, :show, :user_index]
  layout "sidebar_layout_show", only: [:show, :index, :user_index]

  def index
    @posts = Post.all.order(created_at: :desc)
    @events = Event.all.order(created_at: :desc)
    @questions = Question.all.order(created_at: :desc)
    @tasks = Task.all.order(created_at: :desc)

    @users = User.where.not(latitude: nil, longitude: nil)
  end

  def user_index
    @user_posts = Post.where(user: current_user)
    @users = User.where.not(latitude: nil, longitude: nil)
  end

  private

  def localheroes
    # Methods for retrieving top and most recent localheroes
    @top_localheroes = User.order('votes DESC').limit(3)
    @recent_localheroes = User.order('created_at DESC').limit(3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @disable_nav = true
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Mappable
  include Localheroable

  layout "sidebar_layout_show", only: [:show, :index]

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @comment = Comment.new
    # For a comment form
    @post = @question.becomes(Post)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Mappable
  include Localheroable

  layout "sidebar_layout_show", only: [:show, :index]

  before_action :set_task, only: [:update, :show]

  def index
    @tasks = Task.all.order(created_at: :desc)
  end

  def update
    @task.update(done: true)
    redirect_to task_path(@task)
  end

  def show
    @comment = Comment.new
    @post = @task.becomes(Post)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :photo)
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  # Increment given user votes by 1
  def update
    @user = User.find(params[:id])
    redirect_path = Rails.application.routes.recognize_path(params[:back_path])
    @user.upvote!
    redirect_to redirect_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/post_link_helper.rb
module PostLinkHelper
  def determine_post_path(post, param=nil)
    case post
    when Question
      question_path(post, param)
    when Task
      task_path(post, param)
    when Event
      event_path(post, param)
    end
  end
end

app/helpers/post_type_helper.rb
module PostTypeHelper
  def determine_post_type(post)
    case post
    when Question
      post.becomes(Question)
    when Task
      post.becomes(Task)
    when Event
      post.becomes(Event)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />

    <meta property="og:image" content="<%= meta_image %>" />

    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Local Hero - Stronger communities with your neighbours</title>

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar_new' unless @disable_nav %>
    <%= render 'shared/flashes' %>

      <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/sidebar_index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Local Hero</title>
  <%= favicon_link_tag %>

  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>
<body>
  <!-- This is in the index -->
  <%= render 'shared/navbar_new' %>
  <%= render 'shared/flashes' %>

  <div class="container">
    <div class="row">
      <div class="col-3">
        <%= render 'shared/sidebar'%>
      </div>
      <div class="col-9 add-space-index">
        <div class="button-right">
        <%= link_to "Create Post", new_task_path, class: "btn btn-info wide-button" %>
        </div>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/layouts/sidebar_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Local Hero</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>
<body>
  <%= render 'shared/navbar_new' %>
  <%= render 'shared/flashes' %>

  <div class="container">
    <div class="row">
      <div class="col-3">
        <%= render 'shared/sidebar'%>
      </div>
      <div class="col-9 add-space-index">
        <div class="button-right">
        <%= link_to "Create a new post", new_task_path, class: "btn btn-info wide-button" %>
        </div>
        <%= yield %>
      </div>
    </div>
  </div>

  <!-- <div >
   <div class="sidebar">hello</div>
    </div>
    <div>

    </div>
    <div>
  </div> -->
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
 <!--  <script type="text/javascript">
    document.querySelectorAll(".comment-card-upvote a").forEach(function (node) {
      node.addEventListener("click", function(event) {
         event.preventDefault();


      });
    });
  </script> -->
</body>

</html>

<!--
<div class="container">
  <div class="row">
      <div class="col-md-3">
        <div class="sidebar">
        </div>
      </div>
      <div class="col-md-9">
        <div class="main content">
          <div class="row">
            <div class="col-md-4">
          </div>
        </div>
      </div>
      </div>
</div>
 -->

app/views/layouts/sidebar_layout_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Local Hero</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>

  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>
<body>
  <!-- This is in the show -->
  <%= render 'shared/navbar_new' %>
  <%= render 'shared/flashes' %>

  <div class="container">
    <div class="row">
      <div class="col-3">
        <%= render 'shared/sidebar'%>
      </div>
      <div class="col-9 add-space-show">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1528605248644-14dd04022da1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
      <div class="navbar-landing">
          <div class="local-hero">Local Hero</div>
        <div>
          <% unless user_signed_in? %>
          <span><%= link_to "Login", new_user_session_path, class: "landing-login" %></span>
          <% end %>
        </div>
      </div>


    <div class="row">
      <div class="landing-text col-md-6 offset-md-3">

        <h1 id="landing-title">The easiest way to connect with your neighbours</h1>

        <%= link_to "Meet your neighbours", feeds_path,  class: "btn btn-info join-button" %>

      </div>
    </div>
  </div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <div class="icon-card left-card">
        <div class="icon-card-header-flex">
          <%= image_tag "connect.png", class: "info-icon" %>
          <span class="icon-card-header">Connect</span>
        </div>
        <div class="icon-card-content">Discover content only from people within 1 km of your home
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-card center-card">
        <div class="icon-card-header-flex">
          <%= image_tag "reachout.png", class: "info-icon" %>
          <span class="icon-card-header">Reach out</span>
        </div>
        <div class="icon-card-content"> Hosting a local get-together? Need a hand?Unsure about something?</div>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="icon-card right-card">
        <div class="icon-card-header-flex">
          <%= image_tag "reputation.png", class: "info-icon" %>
          <span class="icon-card-header">Earn a reputation</span>
        </div>
        <div class="icon-card-content">Upvote good samaritans or become a local hero in your community</div>
      </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_comment.html.erb
<div class="comment-card">
  <div class="comment-card-avatar">
    <%= cl_image_tag comment.user.photo.url(:bright_face), class: "post-show-avatar" %>
    <% if comment.user.votes >= 30 %>
    <p><%= comment.user.first_name %><span>🏆</span></p>
    <% else %>
    <p><%= comment.user.first_name %></p>

    <% end %>


    <div class="all-cards-upvote">


      <%= render 'shared/upvote', comment: comment %>
    </div>
  </div>
  <div class="comment-card-fixed-body">
    <div class="comment-card-body">
      <p><%= comment.content %></p>
    </div>
    <div class="comment-card-footer">
      <p>Posted <%= comment.created_at.to_formatted_s(:long_ordinal)%></p>
    </div>
  </div>
</div>

app/views/shared/_comments_section.html.erb
<div class="comments-section">
    <h5>Responses</h5>
  <div class="row">
    <% post.comments.each do |comment| %>
      <div class="col-xs-12 col-md-12">
        <%= render 'shared/comment', comment: comment %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div>
        <%= simple_form_for([post, comment], wrapper: :inline_form,
  html: { class: "form-inline" }) do |f| %>
          <%= f.input :content, input_html: {id: "editor"}, wrapper_html: {class: "editor-wrap"}, placeholder: "Write a response" %>
          <%= hidden_field_tag :origin_view, "#{controller_name}/#{action_name}" %>
          <%= f.submit "Post a response", class: "btn btn-info white-text btn-new-post" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- click on write a response label
select the label, input text area, button
event listener - click on the label
opacity 0 toggle class opacity 1 height 50px -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_infowindow.html.erb
<%= link_to event_path(event) do %>
<%= event.title %>
<% end %>

app/views/shared/_navbar_new.html.erb
<div class="navbar bg-white py-2 px-3">
    <%= link_to feeds_path, class: "navbar-logo" do %>
    <div class="nav-bar-right d-flex align-items-center justify-content-around pad">
      <%= image_tag "logo.png", height: 50 %>
      <h3 class="local-hero">Local Hero</h3>
    </div>
    <% end %>

  <div class="nav-bar-right d-flex align-items-center justify-content-around" style="width: 360px" >
    <% if user_signed_in? %>
    <div class="button-right">
        <%= link_to "Howdy Neighbours", new_task_path, class: "btn btn-info wide-button" %>
        </div>

    <div class="d-inline-flex justify-content-around" style="width: 100px">

        <%= link_to "#", class: "px-3 d-none d-sm-block" do %>
          <i class="fas fa-user"></i>
        <% end %>

      <div class="dropdown d-none d-sm-block">
        <i class="fas fa-bell" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.notifications.unread.present? %>
            <i class="fas fa-circle"></i>
          <% end %>
        </i>

        <!-- <#%= current_user.notifications.unread.count %> -->
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <% if current_user.notifications.unread.present? %>
            <% current_user.notifications.unread.each do |n| %>
              <%= link_to notification_path(n), method: :patch, class: "dropdown-item" do %>
                <i class='far fa-comment'></i> <%= n.actor.first_name %> <%= n.action %> on your <%= n.post.type.downcase %>
            <% end %>
            <% end %>
            <% else %>
            <%= link_to "You don't have any notifications", "#", class: "dropdown-item" %>
            <% end %>
        </div>

      </div>
    </div>


    <div class="dropdown  d-none d-sm-block">
      <%= cl_image_tag current_user.photo.url(:bright_face), alt:"avatar", id: "dropdownMenuButton", data: { toggle:"dropdown" }, aria: { haspopup:"true", expanded: "false" } %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">

        <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
      </div>
    </div>
  </div>
  <div class="dropdown burger d-block d-sm-none">
    <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
     <%= link_to "Action", "#", class: "dropdown-item" %>
     <%= link_to "Another action", "#", class: "dropdown-item" %>
     <%= link_to "Something else here", "#", class: "dropdown-item" %>
   </div>
 </div>

  <% else %>

    <%= link_to "Login", new_user_session_path, class: "px-3 d-none d-sm-block" %>
    <%= link_to "Register", new_user_registration_path, class: "px-3 d-none d-sm-block" %>
    <div class="dropdown  d-none d-sm-block">

  <% end %>

    </div>
  </div>
  <div class="dropdown burger d-block d-sm-none">
    <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
     <%= link_to "Action", "#", class: "dropdown-item" %>
     <%= link_to "Another action", "#", class: "dropdown-item" %>
     <%= link_to "Something else here", "#", class: "dropdown-item" %>
   </div>
 </div>

</div>

app/views/shared/_sidebar.html.erb
<div class="card-filter sticky-filter">

  <%= link_to my_posts_path do %>
    <h3 class="card-filter-inside <%= 'active-sidebar' if params[:controller] == 'feeds' && params[:action] == 'user_index' %>">
     My Stuff</h3>
  <% end %>

  <%= link_to feeds_path do %>
    <h3 class="card-filter-inside <%= 'active-sidebar' if params[:controller] == 'feeds' && params[:action] == 'index' %>">All Activity</h3>
  <% end %>

  <%= link_to  tasks_path do %>
    <h3 class="card-filter-inside <%= 'active-sidebar' if params[:controller] == 'tasks'%>">Lend a Hand</h3>
  <% end %>

  <%= link_to questions_path do %>
    <h3 class="card-filter-inside <%= 'active-sidebar' if params[:controller] == 'questions'%>">Ask a Neighbour</h3>
  <% end %>

  <%= link_to events_path do %>
    <h3 class="card-filter-inside last <%= 'active-sidebar' if params[:controller] == 'events'%>">Local Events</h3>
  <% end %>

  <div class="card-map text-dec-none">
    <div class="card-map text-dec-none">
      <% if @markers.present? %>
      <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-eventmarkers="<%= @eventmarkers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
      <% end %>
      <p class="card-map-inside" style="font-size:12px"> There are <%= User.count %> localheroes near you </p>
    </div>


    <div class="card-map text-dec-none">
      <div class="card-map text-dec-none">
          <strong><h2 class="card-leaderboard-infos" id="card-leaderboard-info-header">Top localheroes</h2></strong>
          <ol>
            <% @top_localheroes.each do |localhero| %>
            <li><strong><%= localhero.first_name %> </strong> : <%= localhero.votes %> points</li>
            <% end %>
          </ol>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tabs_new_post.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <strong><a class="nav-link gold-header <%= 'active' if params[:controller] == 'tasks'%>" href="/tasks/new">Ask for a hand</a></strong>
  </li>
  <li class="nav-item">
    <strong><a class="nav-link gold-header <%= 'active' if params[:controller] == 'questions'%>" href="/questions/new">Ask a question</a></strong>
  </li>
  <li class="nav-item">
    <strong><a class="nav-link gold-header <%= 'active' if params[:controller] == 'events'%>" href="/events/new">Create a local event</a></strong>
  </li>
</ul>

app/views/shared/_upvote.html.erb
<%= link_to user_upvote_path(comment.user, back_path: request.path), method: :patch do %>
  <%= comment.user.votes %><i class="fas fa-star"></i>
<% end %>